package ma.enova.radio.workflow.admin.process.histortiqueprescriptionradiotherapie.save;

import ma.enova.radio.zynerator.process.AbstractProcess;

public interface HistortiquePrescriptionRadiotherapieSaveAdminProcess extends AbstractProcess<HistortiquePrescriptionRadiotherapieSaveAdminInput, HistortiquePrescriptionRadiotherapieSaveAdminOutput> {
}
