package ma.enova.radio.workflow.admin.process.prescriptionradiotherapie.validateradiotherapeute;

import ma.enova.radio.zynerator.process.AbstractProcess;

public interface PrescriptionRadiotherapieValidateRadiotherapeuteAdminProcess extends AbstractProcess<PrescriptionRadiotherapieValidateRadiotherapeuteAdminInput, PrescriptionRadiotherapieValidateRadiotherapeuteAdminOutput> {
}
